-- ============================================
-- Script: 05_english_artistas.sql
-- Descripción: Biografías en inglés de los artistas
-- ============================================

USE arte_asturiano;
SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;

UPDATE artistas SET biografia_en = 'Spanish painter specializing in still lifes, flower arrangements, and hunting scenes, who also cultivated landscape and portraiture. She began her training in Madrid under Manuel Ramírez, a teacher at the School of Arts and Crafts. She took part in the National Fine Arts Exhibitions, winning a third-place medal in the 1892 and 1895 editions.' WHERE id = 1;

UPDATE artistas SET biografia_en = 'Prominent visual artist and Doctor in Art History with a career spanning over 40 years. She began experimenting with sculpture at the age of six, under the influence of her artisan grandfather. She trained at the Schools of Applied Arts in Valladolid and Oviedo. She holds a Bachelors degree and a Cum Laude doctorate in Art History from the University of Oviedo. Her work is multidisciplinary, encompassing painting, sculpture, printmaking and photography.' WHERE id = 2;

UPDATE artistas SET biografia_en = 'She was a prominent Spanish painter, a pioneer in the transition from figuration to abstraction within the Asturian post-war art scene. She began her training as a self-taught artist in Gijón. She was a pupil and later the wife of sculptor and painter Joaquín Rubio Camín, with whom she moved to Madrid in 1954. Her work is characterised by a constant evolution from figuration to abstraction.' WHERE id = 3;

UPDATE artistas SET biografia_en = 'Spanish painter of Impressionist and Costumbrist style, a key figure in the renewal of Asturian art in the 20th century. He studied at the San Fernando School of Fine Arts in Madrid under masters such as Carlos de Haes and Antonio Muñoz Degrain, and also in Rome and Paris, where he was influenced by painters like Velázquez, Goya and Whistler. His work reflects popular Asturian scenes and portraits, with a sober colour palette and rigorous drawing.' WHERE id = 4;

UPDATE artistas SET biografia_en = 'He was a Spanish painter and writer, considered one of the most original and innovative figures in Asturian art during the first half of the 20th century. At the age of ten he moved to Puerto Rico with his father. On his return, he worked as a lithographer illustrating graphic magazines such as Blanco y Negro and Madrid Cómico. He suffered from agoraphobia, a condition that worsened after his mother\'s death in 1912. During his years of seclusion he also dedicated himself to writing novels and theatre. His painting is known for its refined use of colour and its originality in portraying Asturian landscapes and folklore, focusing on rural life, peasant types, seascapes and carnival scenes.' WHERE id = 5;

UPDATE artistas SET biografia_en = 'He was a multifaceted Asturian artist, considered one of the most significant sculptors of the second half of the 20th century and one of the few artists to win the National Prize in three different disciplines: painting, sculpture and photography. He initially trained as a painter, influenced by local masters such as Evaristo Valle and Nicanor Piñole. From the 1960s onwards his work turned towards abstract and constructivist sculpture, working with materials such as iron, wood, stone and marble. His work is characterised by geometric rigor and the exploration of space, evolving from figuration towards a sober constructivism.' WHERE id = 6;

UPDATE artistas SET biografia_en = 'He began his relationship with the art world in the studio of Gijón architect Antonio Álvarez Hevia, where he trained as a draftsman alongside Joaquín Rubio Camín. In 1957 he was one of the founding members of the El Paso Group, a collective that introduced informalism and modernism to post-war Spain. His work began with a figurative foundation that evolved towards a highly personal abstraction, moving from the dark tones characteristic of his El Paso period towards a painting of luminous, soft colours and a pronounced visual lyricism.' WHERE id = 7;

UPDATE artistas SET biografia_en = 'He was a key artist and sculptor for the Asturian and Spanish avant-garde of the second half of the 20th century. Born in Madrid, he moved with his family to Gijón at the age of four. In 1952 he returned to the capital to study Civil Engineering and a year later, began studying Architecture, but abandoned both. In the mid-1950s, he returned to Gijón, where he began painting, but his preoccupation with anatomical forms and vital processes led him to sculpture, choosing wood as his primary material.' WHERE id = 8;

UPDATE artistas SET biografia_en = 'He was an Asturian painter and illustrator, a key figure of Asturian regionalist painting in the 20th century alongside artists such as Evaristo Valle and Nicanor Piñole. He was born into a family connected to the graphic arts; his father owned two lithography companies. He began his artistic studies with Nemesio Lavilla at the Ateneo Obrero (Workers\' Athenaeum) in Gijón and later moved to Madrid in 1917 to train in the studio of master Cecilio Plá. His work evolved from a realism with strong social commitment towards a more idealised vision of Asturian landscape and customs. In his early period, he portrayed the harshness of industrial and mining labor with a modern and expressive aesthetic. After the Civil War his style softened, focusing on rural festivals, peasant scenes and coastal landscapes of Asturias.' WHERE id = 9;

UPDATE artistas SET biografia_en = 'He is a prominent Asturian painter and printmaker, a leading figure of the generation that revitalised Spanish painting in the 1980s. He began his training at the Gijón Fine Arts Association and the School of Arts and Crafts in Oviedo. In 1975 he moved to Madrid, where he furthered his studies in printmaking. His work is characterised by a synthesis between figuration and abstraction, with a poetic and often minimalist style.' WHERE id = 10;

SELECT 'Biografías en inglés actualizadas correctamente.' AS Mensaje;
SELECT id, nombre, apellidos, IF(biografia_en IS NOT NULL, 'SÍ', 'NO') AS tiene_biografia_en FROM artistas ORDER BY id;
